"""Synthetic test media.

The pipeline's real input is media the user owns, which cannot be committed. So
the tests build their own: a fake "episode" containing tone bursts at known
timestamps, optionally with a music bed under them, generated by ffmpeg. That
makes the end-to-end test runnable in a fresh clone with nothing but ffmpeg
installed.
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

from waze_voice import media

# (phrase_id, start, end, frequency Hz). Deliberately varied in level and length
# so normalization has something real to correct.
SEGMENTS = [
    ("turn_left", 1.0, 2.1, 320.0),
    ("turn_right", 3.0, 4.2, 400.0),
    ("keep_left", 5.0, 5.9, 480.0),
    ("now", 7.0, 7.6, 560.0),
    ("arrived", 8.5, 10.0, 300.0),
]

SOURCE_SECONDS = 12.0


def make_source_media(destination: Path, *, with_bed: bool = False) -> Path:
    """Render a fake source file with tone bursts at the SEGMENTS timestamps.

    Each burst is given a different gain so the clips arrive at the normalizer
    at genuinely different loudness levels.
    """
    destination.parent.mkdir(parents=True, exist_ok=True)

    inputs: list[str] = []
    parts: list[str] = []
    labels: list[str] = []

    for index, (_, start, end, frequency) in enumerate(SEGMENTS):
        duration = end - start
        inputs += [
            "-f",
            "lavfi",
            "-t",
            f"{duration:.3f}",
            "-i",
            f"sine=frequency={frequency}:sample_rate=44100",
        ]
        # Alternating gain: some clips arrive quiet, some loud.
        gain = -18.0 + (index % 3) * 7.0
        delay_ms = int(start * 1000)
        # Vibrato and tremolo make the burst non-stationary, which matters:
        # a pure steady tone looks exactly like noise to a spectral denoiser,
        # so an unmodulated fixture would test the cleaner against a signal no
        # real recording produces.
        parts.append(
            f"[{index}:a]vibrato=f=6:d=0.5,tremolo=f=5:d=0.5,"
            f"volume={gain}dB,adelay={delay_ms}:all=1,"
            f"apad=whole_dur={SOURCE_SECONDS}[s{index}]"
        )
        labels.append(f"[s{index}]")

    next_index = len(SEGMENTS)
    if with_bed:
        # A continuous low tone standing in for background music.
        inputs += [
            "-f",
            "lavfi",
            "-t",
            f"{SOURCE_SECONDS:.3f}",
            "-i",
            "sine=frequency=110:sample_rate=44100",
        ]
        parts.append(f"[{next_index}:a]volume=-26dB[bed]")
        labels.append("[bed]")
        next_index += 1

    joined = "".join(labels)
    parts.append(f"{joined}amix=inputs={len(labels)}:duration=longest:normalize=0[out]")

    media.run_ffmpeg(
        [
            *inputs,
            "-filter_complex",
            ";".join(parts),
            "-map",
            "[out]",
            "-ac",
            "1",
            "-ar",
            "44100",
            "-t",
            f"{SOURCE_SECONDS:.3f}",
            str(destination),
        ]
    )
    return destination


def make_sources_csv(destination: Path, source_media: Path) -> Path:
    """Write a source inventory CSV pointing at the fake media."""
    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, lineterminator="\n")
        writer.writerow(
            ["phrase_id", "source_path", "start", "end", "take", "preferred", "gain_db", "notes"]
        )
        for phrase_id, start, end, _ in SEGMENTS:
            writer.writerow(
                [phrase_id, str(source_media), f"{start:.3f}", f"{end:.3f}", 1, "", "", "fixture"]
            )
    return destination


def make_phrases_json(destination: Path) -> Path:
    """A phrase inventory covering exactly the fixture segments, plus one gap."""
    destination.parent.mkdir(parents=True, exist_ok=True)
    phrases = [
        {
            "id": phrase_id,
            "label": phrase_id.replace("_", " ").capitalize(),
            "required": True,
            "filename": f"{phrase_id}.mp3",
            "status": "missing",
            "group": "maneuver",
            "order": index,
            "tts_text": "",
            "notes": "",
        }
        for index, (phrase_id, _, _, _) in enumerate(SEGMENTS, start=1)
    ]
    # One required phrase with no source: the case synthesis or manual recording
    # is meant to cover, and which export must report rather than silently drop.
    phrases.append(
        {
            "id": "recalculating",
            "label": "Recalculating",
            "required": True,
            "filename": "recalculating.mp3",
            "status": "missing",
            "group": "misc",
            "order": 1,
            "tts_text": "",
            "notes": "Intentionally has no source row in the fixture.",
        }
    )
    destination.write_text(
        json.dumps({"schema_version": 2, "phrases": phrases}, indent=2) + "\n",
        encoding="utf-8",
    )
    return destination


def make_routes_json(destination: Path) -> Path:
    destination.parent.mkdir(parents=True, exist_ok=True)
    data = {
        "schema_version": 2,
        "routes": [
            {
                "id": "fixture_route",
                "label": "Fixture route",
                "step_gap_seconds": 0.4,
                "phrase_gap_seconds": 0.1,
                "steps": [
                    {"say": ["turn_left"], "context": "first"},
                    {"say": ["now", "turn_right"], "context": "chained"},
                    {"say": ["arrived"]},
                ],
            }
        ],
    }
    destination.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return destination
