"""Synthetic test media.

The pipeline's real input is media the user owns, which cannot be committed. So
the tests build their own: a fake "episode" containing tone bursts at known
timestamps, optionally with a music bed under them, generated by ffmpeg. That
makes the end-to-end test runnable in a fresh clone with nothing but ffmpeg
installed.

The fixture pack is shaped like a real one rather than a uniform set: short
high-priority maneuvers, a long low-priority drive-start greeting, one rarely
heard roundabout ordinal, and both a metric and an imperial distance callout.
That is what makes the budget allocator and the unit-system checks testable.
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

from waze_voice import media

# (phrase_id, waze_filename, units, weight, start, end, frequency Hz)
# Levels are varied by position so normalization has real work to do.
SEGMENTS = [
    ("turn_left", "TurnLeft.mp3", "any", 3.0, 1.0, 2.1, 320.0),
    ("turn_right", "TurnRight.mp3", "any", 3.0, 3.0, 4.2, 400.0),
    ("and_then", "AndThen.mp3", "any", 2.5, 5.0, 5.6, 480.0),
    ("in_quarter_mile", "400.mp3", "imperial", 2.5, 6.5, 7.6, 360.0),
    ("in_400_meters", "400meters.mp3", "metric", 2.5, 8.5, 9.7, 300.0),
    ("arrived", "Arrive.mp3", "any", 2.0, 10.5, 11.9, 260.0),
    # Long and low priority: the clip the weighted allocator should starve.
    ("start_drive_1", "StartDrive1.mp3", "any", 1.0, 12.5, 16.5, 220.0),
    # Short and rare.
    ("exit_seventh", "Seventh.mp3", "any", 0.3, 17.5, 18.5, 540.0),
]

# A core prompt with no source row: the gap synthesis or manual recording covers,
# and which export must report rather than silently drop.
MISSING_PHRASE = ("keep_left", "KeepLeft.mp3", "any", 2.0)

SOURCE_SECONDS = 20.0


def make_source_media(destination: Path, *, with_bed: bool = False) -> Path:
    """Render a fake source file with tone bursts at the SEGMENTS timestamps."""
    destination.parent.mkdir(parents=True, exist_ok=True)

    inputs: list[str] = []
    parts: list[str] = []
    labels: list[str] = []

    for index, (_, _, _, _, start, end, frequency) in enumerate(SEGMENTS):
        duration = end - start
        inputs += [
            "-f",
            "lavfi",
            "-t",
            f"{duration:.3f}",
            "-i",
            f"sine=frequency={frequency}:sample_rate=44100",
        ]
        # Alternating gain: some clips arrive quiet, some loud.
        gain = -18.0 + (index % 3) * 7.0
        delay_ms = int(start * 1000)
        # Vibrato and tremolo make the burst non-stationary, which matters: a
        # pure steady tone looks exactly like noise to a spectral denoiser, so an
        # unmodulated fixture would test the cleaner against a signal no real
        # recording produces.
        parts.append(
            f"[{index}:a]vibrato=f=6:d=0.5,tremolo=f=5:d=0.5,"
            f"volume={gain}dB,adelay={delay_ms}:all=1,"
            f"apad=whole_dur={SOURCE_SECONDS}[s{index}]"
        )
        labels.append(f"[s{index}]")

    next_index = len(SEGMENTS)
    if with_bed:
        # A continuous low tone standing in for background music.
        inputs += [
            "-f",
            "lavfi",
            "-t",
            f"{SOURCE_SECONDS:.3f}",
            "-i",
            "sine=frequency=110:sample_rate=44100",
        ]
        parts.append(f"[{next_index}:a]volume=-26dB[bed]")
        labels.append("[bed]")
        next_index += 1

    joined = "".join(labels)
    parts.append(f"{joined}amix=inputs={len(labels)}:duration=longest:normalize=0[out]")

    media.run_ffmpeg(
        [
            *inputs,
            "-filter_complex",
            ";".join(parts),
            "-map",
            "[out]",
            "-ac",
            "1",
            "-ar",
            "44100",
            "-t",
            f"{SOURCE_SECONDS:.3f}",
            str(destination),
        ]
    )
    return destination


def make_sources_csv(destination: Path, source_media: Path) -> Path:
    """Write a source inventory CSV pointing at the fake media."""
    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, lineterminator="\n")
        writer.writerow(
            ["phrase_id", "source_path", "start", "end", "take", "preferred", "gain_db", "notes"]
        )
        for phrase_id, _, _, _, start, end, _ in SEGMENTS:
            writer.writerow(
                [phrase_id, str(source_media), f"{start:.3f}", f"{end:.3f}", 1, "", "", "fixture"]
            )
    return destination


def make_phrases_json(destination: Path) -> Path:
    """A phrase inventory covering the fixture segments, plus one missing core prompt."""
    destination.parent.mkdir(parents=True, exist_ok=True)

    phrases = []
    for order, (phrase_id, waze, units, weight, _, _, _) in enumerate(SEGMENTS, start=1):
        phrases.append(
            {
                "id": phrase_id,
                "label": phrase_id.replace("_", " ").capitalize(),
                "required": True,
                "filename": f"{phrase_id}.mp3",
                "status": "missing",
                "group": "maneuver",
                "order": order,
                "tts_text": "",
                "notes": "",
                "waze_filename": waze,
                "units": units,
                "weight": weight,
            }
        )

    phrase_id, waze, units, weight = MISSING_PHRASE
    phrases.append(
        {
            "id": phrase_id,
            "label": phrase_id.replace("_", " ").capitalize(),
            "required": True,
            "filename": f"{phrase_id}.mp3",
            "status": "missing",
            "group": "maneuver",
            "order": len(SEGMENTS) + 1,
            "tts_text": "",
            "notes": "Intentionally has no source row in the fixture.",
            "waze_filename": waze,
            "units": units,
            "weight": weight,
        }
    )

    destination.write_text(
        json.dumps({"schema_version": 3, "phrases": phrases}, indent=2) + "\n",
        encoding="utf-8",
    )
    return destination


def make_routes_json(destination: Path) -> Path:
    destination.parent.mkdir(parents=True, exist_ok=True)
    data = {
        "schema_version": 3,
        "routes": [
            {
                "id": "fixture_route",
                "label": "Fixture route",
                "step_gap_seconds": 0.4,
                "phrase_gap_seconds": 0.1,
                "steps": [
                    {"say": ["turn_left"], "context": "first"},
                    {"say": ["in_quarter_mile", "turn_right"], "context": "chained"},
                    {"say": ["arrived"]},
                ],
            }
        ],
    }
    destination.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return destination
